/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R4weblabRouteImport } from './routes/4weblab'
import { Route as ChiSonoRouteImport } from './routes/chi-sono'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as GinoideAndroideTestRouteImport } from './routes/ginoide-androide-test'
import { Route as PartnershipRouteImport } from './routes/partnership'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ServiziEpTeamRouteImport } from './routes/servizi-ep-team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R4weblabRoute = R4weblabRouteImport.update({
  id: '/4weblab',
  path: '/4weblab',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSonoRoute = ChiSonoRouteImport.update({
  id: '/chi-sono',
  path: '/chi-sono',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const GinoideAndroideTestRoute = GinoideAndroideTestRouteImport.update({
  id: '/ginoide-androide-test',
  path: '/ginoide-androide-test',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipRoute = PartnershipRouteImport.update({
  id: '/partnership',
  path: '/partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziEpTeamRoute = ServiziEpTeamRouteImport.update({
  id: '/servizi-ep-team',
  path: '/servizi-ep-team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/4weblab': typeof R4weblabRoute
  '/chi-sono': typeof ChiSonoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/ginoide-androide-test': typeof GinoideAndroideTestRoute
  '/partnership': typeof PartnershipRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/servizi-ep-team': typeof ServiziEpTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/4weblab': typeof R4weblabRoute
  '/chi-sono': typeof ChiSonoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/ginoide-androide-test': typeof GinoideAndroideTestRoute
  '/partnership': typeof PartnershipRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/servizi-ep-team': typeof ServiziEpTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/4weblab': typeof R4weblabRoute
  '/chi-sono': typeof ChiSonoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/ginoide-androide-test': typeof GinoideAndroideTestRoute
  '/partnership': typeof PartnershipRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/servizi-ep-team': typeof ServiziEpTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/4weblab'
    | '/chi-sono'
    | '/contatti'
    | '/cookie-policy'
    | '/ginoide-androide-test'
    | '/partnership'
    | '/privacy-policy'
    | '/servizi-ep-team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/4weblab'
    | '/chi-sono'
    | '/contatti'
    | '/cookie-policy'
    | '/ginoide-androide-test'
    | '/partnership'
    | '/privacy-policy'
    | '/servizi-ep-team'
  id:
    | '__root__'
    | '/'
    | '/4weblab'
    | '/chi-sono'
    | '/contatti'
    | '/cookie-policy'
    | '/ginoide-androide-test'
    | '/partnership'
    | '/privacy-policy'
    | '/servizi-ep-team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R4weblabRoute: typeof R4weblabRoute
  ChiSonoRoute: typeof ChiSonoRoute
  ContattiRoute: typeof ContattiRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  GinoideAndroideTestRoute: typeof GinoideAndroideTestRoute
  PartnershipRoute: typeof PartnershipRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServiziEpTeamRoute: typeof ServiziEpTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/4weblab': {
      id: '/4weblab'
      path: '/4weblab'
      fullPath: '/4weblab'
      preLoaderRoute: typeof R4weblabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-sono': {
      id: '/chi-sono'
      path: '/chi-sono'
      fullPath: '/chi-sono'
      preLoaderRoute: typeof ChiSonoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ginoide-androide-test': {
      id: '/ginoide-androide-test'
      path: '/ginoide-androide-test'
      fullPath: '/ginoide-androide-test'
      preLoaderRoute: typeof GinoideAndroideTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnership': {
      id: '/partnership'
      path: '/partnership'
      fullPath: '/partnership'
      preLoaderRoute: typeof PartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi-ep-team': {
      id: '/servizi-ep-team'
      path: '/servizi-ep-team'
      fullPath: '/servizi-ep-team'
      preLoaderRoute: typeof ServiziEpTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R4weblabRoute: R4weblabRoute,
  ChiSonoRoute: ChiSonoRoute,
  ContattiRoute: ContattiRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  GinoideAndroideTestRoute: GinoideAndroideTestRoute,
  PartnershipRoute: PartnershipRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServiziEpTeamRoute: ServiziEpTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
